#!/usr/bin/env php
<?php declare(strict_types=1);

use LaravelExpansions\Function\Types\Event;

define('LARAVEL_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

/**
 * lambda handler
 * 
 * @param object $event
 */
return function ($event) {
    return (new Event($event))->dispatch();
};
